services:
  disk_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=appcore.settings
    command: >
      sh -c "python appcore/manage.py migrate &&
             python appcore/manage.py runserver 0.0.0.0:8000"